services:
  redis:
    image: redis:7-alpine
    container_name: cache-aside-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - cache-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cache-aside-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - cache-network

  postgres:
    image: postgres:latest
    container_name: cache-aside-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cache-aside-app
    ports:
      - "5432:5432"
    volumes:
      - cache-aside-postgres-data:/var/lib/postgresql/data

volumes:
  redis_data:
    driver: local
  cache-aside-postgres-data:
    driver: local

networks:
  cache-network:
    driver: bridge
